/*
 * generated by Xtext 2.13.0
 */
package it.imt.ide

import com.google.inject.Guice
import it.imt.QFLanRuntimeModule
import it.imt.QFLanStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class QFLanIdeSetup extends QFLanStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new QFLanRuntimeModule, new QFLanIdeModule))
	}
	
}
