/*
 * generated by Xtext 2.24.0
 */
package it.imt.ui.tests;

import com.google.inject.Injector;
import it.imt.qflan.xtext.ui.internal.XtextActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class QFLanUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("it.imt.QFLan");
	}

}
