/*
 * generated by Xtext 2.13.0
 */
package it.imt


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class QFLanStandaloneSetup extends QFLanStandaloneSetupGenerated {

	def static void doSetup() {
		new QFLanStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
